version: '3.3'
services:
    app-apache:
        container_name: app-logic
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - mysql_db
        volumes:
            - ./src:/var/www/html/
        networks:
             intranet1:
                ipv4_address: 10.1.2.2
        ports:
            - 80:80
        expose:
          - 80

   
    keyrock:
        image: fiware/idm:7.8.1
        container_name: keyrock
        hostname: keyrock
        depends_on: 
           - mysql_db
        ports:
           - 3005:3005
           - 443:443
        networks:
          intranet1:
           ipv4_address: 10.1.2.5
        environment:
           - IDM_DB_HOST=mysql_db
           - IDM_DB_USER=keyrock
           - IDM_DB_PASS=keyrock
           - IDM_HOST=http://localhost:3005
           - IDM_PORT=3005
           - IDM_ADMIN_USER=admin
           - IDM_ADMIN_EMAIL=l@tuc.gr
           - IDM_ADMIN_PASS=admin
  
    mysql_db:
        container_name: mysql_db        
        hostname: mysql_db
        image: mysql:5.7
        restart: always
        expose:
          - "3306"
        ports:
          - "3306:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./sql_init:/var/lib/init
        command: mysqld --init-file="/var/lib/init/idm.sql" --max_allowed_packet=32505856  
        environment:
          - "MYSQL_ROOT_PASSWORD= secret"
          - "MYSQL_ROOT_HOST= 10.1.2.5"
        networks:
           intranet1:
              ipv4_address: 10.1.2.6

    data-storage:
        container_name: data-storage
        hostname: data-storage
        build:
          context: ./
          dockerfile: Dockerfile_mongo
        
        networks:
           intranet1:
              ipv4_address: 10.1.2.3
        expose:
          - 80
    
    data-storage-proxy:
        image: fiware/pep-proxy
        container_name: data-storage-proxy
        hostname: data-storage-proxy
        networks:
            intranet1:
              ipv4_address: 10.1.2.4
        ports:
          - 4001:4001
        expose:
          - 4001
        depends_on:
          - keyrock
        environment:
          - PEP_PROXY_APP_HOST=data-storage
          - PEP_PROXY_APP_PORT=80
          - PEP_PROXY_PORT=4001
          - PEP_PROXY_IDM_HOST=keyrock
          - PEP_PROXY_HTTPS_ENABLED=false
          - PEP_PROXY_AUTH_ENABLED=false
          - PEP_PROXY_IDM_SSL_ENABLED=false
          - PEP_PROXY_IDM_PORT=3005
          - PEP_PROXY_APP_ID=d6e57ccf-9261-4ec7-a8da-bd9494871e4e
          - PEP_PROXY_USERNAME=pep_proxy_6b7a2797-000c-4690-b583-4975aa1046d7
          - PEP_PASSWORD=pep_proxy_5725acce-ba06-4fa3-843c-5a9b6d97cb19
          - PEP_PROXY_PDP=idm


    mongo:
         image: mongo:latest
         container_name: mongodb
         restart: always
         volumes:
           - ./mongodb_data:/data/db
         environment:
           MONGO_INITDB_ROOT_USERNAME: admin
           MONGO_INITDB_ROOT_PASSWORD: admin
         ports: 
           - "27018:27017"
         expose: 
            - 27018
         networks:
            intranet1:
               ipv4_address: 10.1.2.7
    orion-proxy:
        image: fiware/pep-proxy
        container_name: orion-proxy
        hostname: orion-proxy
        networks:
           intranet1:
              ipv4_address: 10.1.2.11
        ports:
          - 4002:4002
        expose:
          - 4002
        depends_on:
          - keyrock
        environment:
          - PEP_PROXY_APP_HOST=orion
          - PEP_PROXY_APP_PORT=1026
          - PEP_PROXY_PORT=4002
          - PEP_PROXY_IDM_HOST=keyrock
          - PEP_PROXY_HTTPS_ENABLED=false
          - PEP_PROXY_AUTH_ENABLED=false
          - PEP_PROXY_IDM_SSL_ENABLED=false
          - PEP_PROXY_IDM_PORT=3005
          - PEP_PROXY_APP_ID=d6e57ccf-9261-4ec7-a8da-bd9494871e4e
          - PEP_PROXY_USERNAME=pep_proxy_6b7a2797-000c-4690-b583-4975aa1046d7
          - PEP_PASSWORD=pep_proxy_5725acce-ba06-4fa3-843c-5a9b6d97cb19
          - PEP_PROXY_PDP=idm

    orion-mongo:
        image: mongo:latest
        container_name: mongodb-orion
        restart: always
        volumes:
           - ./mongodb_orion_data/database:/data/db
        environment:
           MONGO_INITDB_ROOT_USERNAME: admin
           MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
           - 27017:27017
        expose:
           - 27017
        networks:
           intranet1:
               ipv4_address: 10.1.2.8


    orion:
        image: fiware/orion
        hostname: orion
        container_name: orion
        links:
           - orion-mongo
        command: -dbhost orion-mongo -dbuser admin -dbpwd admin
        networks:
           intranet1:
              ipv4_address: 10.1.2.10
        expose:
           - 1026
              
    phpmyadmin:
        container_name: sql-admin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
          PMA_HOST: mysql_db
        depends_on:
            - mysql_db
        networks:
           intranet1:
              ipv4_address: 10.1.2.9
networks:
    intranet1:
      ipam:
        config:
          - subnet: 10.1.2.0/24