version: '3.3'
services:
    app-apache:
        container_name: app-logic
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - mysql_db
        volumes:
            - ./src:/var/www/html/
        networks:
             intranet1:
                ipv4_address: 10.1.2.2
        ports:
            - 80:80
   
    keyrock:
        image: fiware/idm:7.8.1
        container_name: keyrock
        hostname: keyrock
        depends_on: 
           - mysql_db
        ports:
           - 3005:3005
           - 443:443
        networks:
          intranet1:
           ipv4_address: 10.1.2.5
        environment:
           - IDM_DB_HOST=mysql_db
           - IDM_DB_USER=keyrock
           - IDM_DB_PASS=keyrock
           - IDM_HOST=http://localhost:3005
           - IDM_PORT=3005
           - IDM_ADMIN_USER=admin
           - IDM_ADMIN_EMAIL=l@tuc.gr
           - IDM_ADMIN_PASS=admin
  
    mysql_db:
        container_name: mysql_db        
        hostname: mysql_db
        image: mysql:5.7
        restart: always
        expose:
          - "3306"
        ports:
          - "3306:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql
        environment:
          - "MYSQL_ROOT_PASSWORD= secret"
          - "MYSQL_ROOT_HOST= 10.1.2.5"
        networks:
           intranet1:
              ipv4_address: 10.1.2.6
    data-storage:
        container_name: data-storage
        hostname: data-storage
        build:
          context: ./
          dockerfile: Dockerfile_mongo
        
        networks:
           intranet1:
              ipv4_address: 10.1.2.3
        expose:
          - 80
    mongo:
        image: mongo:latest
        container_name: mongodb
        restart: always
        volumes:
           - ./mongodb_data:/data/db
        environment:
           MONGO_INITDB_ROOT_USERNAME: admin
           MONGO_INITDB_ROOT_PASSWORD: admin
        ports: 
           - 27018:27017
        expose:
           - 27017
        networks:
            intranet1:
               ipv4_address: 10.1.2.7
    dss-proxy:
        image: fiware/pep-proxy
        container_name: dss-proxy
        hostname: dss-proxy
        networks:
            intranet1:
              ipv4_address: 10.1.2.4
        ports:
          - 4001:4001
        expose:
          - 4001
        depends_on:
          - keyrock
        environment:
          - PEP_PROXY_APP_HOST=dss-core
          - PEP_PROXY_APP_PORT=80
          - PEP_PROXY_PORT=4001
          - PEP_PROXY_IDM_HOST=keyrock
          - PEP_PROXY_HTTPS_ENABLED=false
          - PEP_PROXY_AUTH_ENABLED=false
          - PEP_PROXY_IDM_SSL_ENABLED=false
          - PEP_PROXY_IDM_PORT=3005
          - PEP_PROXY_APP_ID=803f4f84-c658-4c56-88bd-cebedf07eb24
          - PEP_PROXY_USERNAME=pep_proxy_f49e9df7-e0c4-46a8-bb3b-bb9305fc4e8e
          - PEP_PASSWORD=pep_proxy_a16411d8-7512-4395-bf49-3e0b373175f6
          - PEP_PROXY_PDP=idm
              
    phpmyadmin:
        container_name: sql-admin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
          PMA_HOST: mysql_db
        depends_on:
            - mysql_db
        networks:
           intranet1:
              ipv4_address: 10.1.2.9
networks:
    intranet1:
      ipam:
        config:
          - subnet: 10.1.2.0/24